### ISSUE TITLE
State not reset by clr button

### ISSUE THREAD

**Issue by rjswenson** [chozandrias76/calculator-app#1]
Expected:  
Clicking clear resets state back to the beginning.  Therefore no calculation would happen on clicking =, the value displayed should be zero, and if you do a calculation it should calculate from 0.

Actual:
Seems that if you lose state at any point, the clear button doesn't get you back to reset.

**Comment by chozandrias76** [comment]
Another unintended consequence I am looking into. Will update when most of the issues around this are resolved.

**Comment by chozandrias76** [comment]
Fixed in recent commits.
